# -*- coding: utf-8 -*-
"""Copy of Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xHZYdk5_49mHdpdz15CzeEloy8DSh7VD
"""

import pandas as pd

fear_greed = pd.read_csv('/content/fear_greed_index.csv')
trades = pd.read_csv('/content/historical_data (2).csv')

fear_greed['date'] = pd.to_datetime(fear_greed['date'])
trades['Timestamp IST'] = pd.to_datetime(trades['Timestamp IST'], errors='coerce')
trades['date'] = trades['Timestamp IST'].dt.date

# Convert both columns to datetime
fear_greed['date'] = pd.to_datetime(fear_greed['date'], errors='coerce')
trades['Timestamp IST'] = pd.to_datetime(trades['Timestamp IST'], errors='coerce')

# Create a clean 'date' column in trades with only the date part
trades['date'] = trades['Timestamp IST'].dt.date

# Convert 'date' column in trades also to datetime64 (important!)
trades['date'] = pd.to_datetime(trades['date'])



merged = pd.merge(trades, fear_greed, how='inner', on='date')

sentiment_analysis = merged.groupby('classification').agg({
    'Closed PnL': ['mean', 'sum'],
    'Size USD': 'mean',
    'Start Position': 'mean',
}).reset_index()

import os
import seaborn as sns
import matplotlib.pyplot as plt

# Create the folder if it doesn't exist
os.makedirs('outputs', exist_ok=True)

# Create the bar plot
sns.barplot(data=sentiment_analysis, x='classification', y=('Closed PnL', 'mean'));

# Add title and labels
plt.title('Average Profit in Fear vs Greed Periods')
plt.xlabel('Market Sentiment')
plt.ylabel('Average Closed PnL')

# Save and show the plot
plt.savefig('outputs/sentiment_vs_profit.png', bbox_inches='tight')
plt.show()