# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rWsVu2RR4Cd1b8zEbkfrxRtxpY6hC4QG
"""

import pandas as pd
btc_sent = pd.read_csv('/content/fear_greed_index.csv')
trades = pd.read_csv('/content/historical_data (2).csv')

print(trades.shape)
trades.info()
trades.isna().sum()
trades.head()

print(btc_sent.shape)
btc_sent.info()
btc_sent.isna().sum()
btc_sent.head()

# Ensure the 'Start Position' and 'Closed PnL' columns are numeric
# 'errors="coerce"' will convert non-numeric values to NaN
trades['Start Position'] = pd.to_numeric(trades['Start Position'], errors='coerce')
trades['Closed PnL'] = pd.to_numeric(trades['Closed PnL'], errors='coerce')

def format_large_number(num):
    if abs(num) >= 1_000_000_000:
        return f"{round(num/1_000_000_000, 2)}b"
    elif abs(num) >= 1_000_000:
        return f"{round(num/1_000_000, 2)}m"
    elif abs(num) >= 1_000:
        return f"{round(num/1_000, 2)}k"
    else:
        return str(round(num, 2))

# 1 Calculate and print total number of trades
total_trades = trades.shape[0]
print(f"Total trades: {total_trades}")

# 2️ Calculate and print mean leverage
mean_leverage = trades['Start Position'].mean()
print(f"Mean leverage: {format_large_number(mean_leverage)}")

# 3️ Calculate and print overall profit/loss with conditional message
overall_pnl = trades['Closed PnL'].sum()
if overall_pnl > 0:
    print(f"Overall PnL: +${format_large_number(overall_pnl)} (Profit)")
elif overall_pnl < 0:
    print(f"Overall PnL: -${format_large_number(abs(overall_pnl))} (Loss)")
else:
    print(f"Overall PnL: ${format_large_number(overall_pnl)} (Break-even)")

# 4️ Calculate and print win rate percentage
win_rate = (trades['Closed PnL'] > 0).mean() * 100
print(f"Win rate: {round(win_rate, 2)}%")

# Donut for Win Rate
plt.figure(figsize=(5,5))
colors = ['green', 'lightgrey']
plt.pie([win_rate, 100-win_rate], labels=['Wins', 'Losses'], autopct='%1.1f%%', colors=colors, startangle=90, wedgeprops={'width':0.3})
plt.title("Win Rate", fontsize=14)
plt.show()

import matplotlib.pyplot as plt

# Function to format large numbers
def format_large_number(num):
    if abs(num) >= 1_000_000_000:
        return f"{round(num/1_000_000_000, 2)}b"
    elif abs(num) >= 1_000_000:
        return f"{round(num/1_000_000, 2)}m"
    elif abs(num) >= 1_000:
        return f"{round(num/1_000, 2)}k"
    else:
        return str(round(num, 2))

import matplotlib.pyplot as plt

# Function to format large numbers into k/m/b
def format_large_number(num):
    if abs(num) >= 1_000_000_000:
        return f"{round(num/1_000_000_000, 2)}b"
    elif abs(num) >= 1_000_000:
        return f"{round(num/1_000_000, 2)}m"
    elif abs(num) >= 1_000:
        return f"{round(num/1_000, 2)}k"
    else:
        return str(round(num, 2))

# Dashboard: 4 KPIs in 2x2 layout
fig, axes = plt.subplots(2, 2, figsize=(12, 7))

# 1️⃣ Total Trades
axes[0,0].text(0.5, 0.5, f"{total_trades}", fontsize=30, ha='center', va='center', color='blue')
axes[0,0].set_title("Total Trades", fontsize=14)
axes[0,0].axis('off')

# 2️⃣ Mean Leverage
axes[0,1].text(0.5, 0.5, f"{format_large_number(mean_leverage)}", fontsize=30, ha='center', va='center', color='orange')
axes[0,1].set_title("Mean Leverage", fontsize=14)
axes[0,1].axis('off')

# 3️⃣ Overall PnL
color = 'green' if overall_pnl >= 0 else 'red'
sign = '+' if overall_pnl >= 0 else '-'
axes[1,0].text(0.5, 0.5, f"{sign}${format_large_number(abs(overall_pnl))}", fontsize=30, ha='center', va='center', color=color)
axes[1,0].set_title("Overall PnL", fontsize=14)
axes[1,0].axis('off')

# 4️⃣ Win Rate
axes[1,1].text(0.5, 0.5, f"{round(win_rate,2)}%", fontsize=30, ha='center', va='center', color='purple')
axes[1,1].set_title("Win Rate", fontsize=14)
axes[1,1].axis('off')

# Add a main title for the dashboard
plt.suptitle("Trading Performance Insights", fontsize=18, fontweight='bold')

# Adjust layout so the main title and panels do not overlap
plt.tight_layout(rect=[0, 0, 1, 0.95])

# Display the dashboard
plt.show()

# Clean column names: lowercase, replace spaces with underscores
trades.columns = trades.columns.str.strip().str.lower().str.replace(' ', '_')

# Convert numeric columns (size, price, pnl, fee) to float
num_cols = ['execution_price','size_tokens','size_usd','start_position','closed_pnl','fee','trade_id']
for col in num_cols:
    trades[col] = pd.to_numeric(trades[col], errors='coerce')

# Convert timestamp to datetime
trades['timestamp_ist'] = pd.to_datetime(trades['timestamp_ist'], errors='coerce')

# Quick check for missing values
trades.isna().sum()

# Standardize column names
btc_sent.columns = btc_sent.columns.str.strip().str.lower().str.replace(' ', '_')
print(btc_sent.columns)

daily = daily.merge(
    btc_sent[['date', 'classification']],  # lowercase name
    on='date',
    how='left'
).rename(columns={'classification':'sentiment'})

daily = trades.groupby('date').agg(
    total_trades=('account', 'count'),                  # total trades executed
    total_volume_usd=('size_usd', 'sum'),              # total traded USD
    avg_leverage=('start_position', 'mean'),           # average leverage (use start_position as proxy)
    win_trades=('closed_pnl', lambda x: (x>0).sum()), # number of profitable trades
    loss_trades=('closed_pnl', lambda x: (x<0).sum()),# number of losing trades
    total_pnl=('closed_pnl','sum'),                    # total profit/loss
    avg_pnl=('closed_pnl','mean')                      # average profit/loss per trade
).reset_index()

daily['win_rate'] = daily['win_trades'] / daily['total_trades'] # proportion of winning trades

# Basic daily stats
print("Overall daily stats:")
print(daily[['total_trades','total_volume_usd','avg_leverage','total_pnl','win_rate']].describe())